// Code generated by protoc-gen-go.
// source: zipcode.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	zipcode.proto

It has these top-level messages:
	ZipCode
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ZipCode struct {
	Name      string `protobuf:"bytes,1,opt,name=Name"        json:"行政區名,omitempty"                    xml:"行政區名,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=Code"        json:"_x0033_碼郵遞區號,omitempty"            xml:"_x0033_碼郵遞區號,omitempty"`
	Longitude string `protobuf:"bytes,3,opt,name=Longitude"   json:"中心點經度,omitempty"                   xml:"中心點經度,omitempty"`
	Latitude  string `protobuf:"bytes,4,opt,name=Latitude"    json:"中心點緯度,omitempty"                   xml:"中心點緯度,omitempty"`
	TgosURL   string `protobuf:"bytes,5,opt,name=TgosURL"     json:"TGOS_URL,omitempty"                xml:"TGOS_URL,omitempty"`
}

func (m *ZipCode) Reset()                    { *m = ZipCode{} }
func (m *ZipCode) String() string            { return proto.CompactTextString(m) }
func (*ZipCode) ProtoMessage()               {}
func (*ZipCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ZipCode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZipCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ZipCode) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *ZipCode) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *ZipCode) GetTgosURL() string {
	if m != nil {
		return m.TgosURL
	}
	return ""
}

func init() {
	proto.RegisterType((*ZipCode)(nil), "beans.ZipCode")
}

func init() { proto.RegisterFile("zipcode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xad, 0xca, 0x2c, 0x48,
	0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4a, 0x4d, 0xcc, 0x2b,
	0x56, 0x6a, 0x65, 0xe4, 0x62, 0x8f, 0xca, 0x2c, 0x70, 0xce, 0x4f, 0x49, 0x15, 0x12, 0xe2, 0x62,
	0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x20,
	0x39, 0x09, 0x26, 0x88, 0x18, 0x58, 0x9d, 0x0c, 0x17, 0xa7, 0x4f, 0x7e, 0x5e, 0x7a, 0x66, 0x49,
	0x69, 0x4a, 0xaa, 0x04, 0x33, 0x58, 0x02, 0x21, 0x20, 0x24, 0xc5, 0xc5, 0xe1, 0x93, 0x58, 0x02,
	0x91, 0x64, 0x01, 0x4b, 0xc2, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0x21, 0xe9, 0xf9, 0xc5, 0xa1, 0x41,
	0x3e, 0x12, 0xac, 0x60, 0x29, 0x18, 0x37, 0x89, 0x0d, 0xec, 0x2a, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x37, 0x64, 0x12, 0x9a, 0xa6, 0x00, 0x00, 0x00,
}
