// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zipcode.proto

package beans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZipCode struct {
	// @inject_tag: json:"行政區名,omitempty"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"行政區名,omitempty"`
	// @inject_tag: json:"_x0033_碼郵遞區號,omitempty"
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"_x0033_碼郵遞區號,omitempty"`
	// @inject_tag: json:"中心點經度,omitempty"
	Longitude string `protobuf:"bytes,3,opt,name=longitude,proto3" json:"中心點經度,omitempty"`
	// @inject_tag: json:"中心點緯度,omitempty"
	Latitude string `protobuf:"bytes,4,opt,name=latitude,proto3" json:"中心點緯度,omitempty"`
	// @inject_tag: json:"TGOS_URL,omitempty"
	TgosURL              string   `protobuf:"bytes,5,opt,name=tgosURL,proto3" json:"TGOS_URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZipCode) Reset()         { *m = ZipCode{} }
func (m *ZipCode) String() string { return proto.CompactTextString(m) }
func (*ZipCode) ProtoMessage()    {}
func (*ZipCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb1b31f6378fe412, []int{0}
}

func (m *ZipCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZipCode.Unmarshal(m, b)
}
func (m *ZipCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZipCode.Marshal(b, m, deterministic)
}
func (m *ZipCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZipCode.Merge(m, src)
}
func (m *ZipCode) XXX_Size() int {
	return xxx_messageInfo_ZipCode.Size(m)
}
func (m *ZipCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ZipCode.DiscardUnknown(m)
}

var xxx_messageInfo_ZipCode proto.InternalMessageInfo

func (m *ZipCode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZipCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ZipCode) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *ZipCode) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *ZipCode) GetTgosURL() string {
	if m != nil {
		return m.TgosURL
	}
	return ""
}

func init() {
	proto.RegisterType((*ZipCode)(nil), "beans.ZipCode")
}

func init() { proto.RegisterFile("zipcode.proto", fileDescriptor_fb1b31f6378fe412) }

var fileDescriptor_fb1b31f6378fe412 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xad, 0xca, 0x2c, 0x48,
	0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4a, 0x4d, 0xcc, 0x2b,
	0x56, 0x6a, 0x65, 0xe4, 0x62, 0x8f, 0xca, 0x2c, 0x70, 0xce, 0x4f, 0x49, 0x15, 0x12, 0xe2, 0x62,
	0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x20,
	0x4d, 0x12, 0x4c, 0x10, 0x31, 0x10, 0x5b, 0x48, 0x86, 0x8b, 0x33, 0x27, 0x3f, 0x2f, 0x3d, 0xb3,
	0xa4, 0x34, 0x25, 0x55, 0x82, 0x19, 0x2c, 0x81, 0x10, 0x10, 0x92, 0xe2, 0xe2, 0xc8, 0x49, 0x2c,
	0x81, 0x48, 0xb2, 0x80, 0x25, 0xe1, 0x7c, 0x21, 0x09, 0x2e, 0xf6, 0x92, 0xf4, 0xfc, 0xe2, 0xd0,
	0x20, 0x1f, 0x09, 0x56, 0xb0, 0x14, 0x8c, 0x9b, 0xc4, 0x06, 0x76, 0x95, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x01, 0x6c, 0x7b, 0xe0, 0xa6, 0x00, 0x00, 0x00,
}
